name: "Chromatic"
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Specify Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn

      - name: Run Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
